version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: godlevel-postgres
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cube:
    image: cubejs/cube:latest
    container_name: godlevel-cube
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: challenge_db
      CUBEJS_DB_USER: challenge
      CUBEJS_DB_PASS: challenge_2024
      CUBEJS_API_SECRET: super_secret_long_123
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ../cube:/cube/conf

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: godlevel-api
    environment:
      DATABASE_URL: postgresql+psycopg://challenge:challenge_2024@postgres:5432/challenge_db
      CUBE_API_URL: http://cube:4000/cubejs-api
      CUBE_API_TOKEN: super_secret_long_123
      JWT_SECRET: coloque_um_grande_aqui_____________________________
      JWT_REFRESH_SECRET: outro_grande________________________________
      JWT_SHARE_SECRET: outro_mais___________________________________
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      CACHE_MAX_AGE: "60"
      CACHE_SWR: "300"
      ENV: development
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - cube

volumes:
  postgres-data:
